env:
  browser: true
  es6: true
  jest: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: '16.13.0'
rules:
  '@typescript-eslint/explicit-function-return-type': 'off'
